services:
  ganvil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ganvil_container
    ports:
      - "1303:1303"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped